version: '3.6'

services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - .:/app/backend
    command: python main.py
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - .:/appFront/frontend
    links:
      - backend
    command: npm run start
